---
- name: "{{ ansible_host }} - Disable http server"
  cisco.ios.ios_config:
    lines: no ip http server
  register: http_result

- name: "{{ ansible_host }} Check HTTP server status"
  cisco.ios.ios_command:
    commands: show ip http server status
  register: check_http

- name: "{{ ansible_host }} Assert HTTP server is disabled"
  ansible.builtin.assert:
    that: "'Disabled' in check_http.stdout_lines[0][0]"
    fail_msg: "HTTP state is NOT disabled"
    success_msg: "HTTP state is disabled"
