---
- name: "{{ ansible_host }} Check current HTTP server status"
  cisco.ios.ios_command:
    commands:
      - show ip http server status
  register: check_http

- name: "{{ ansible_host }} Print current HTTP server status"
  debug:
    msg: "{{ check_http.stdout_lines[0][0] }}"

- include_tasks:
    file: "{{ state }}.yml"
  when: state is defined

- name: "{{ ansible_host }} Print verbose HTTP server status"
  debug:
    msg: "{{ check_http.stdout_lines }}"
