---
- ansible.builtin.import_role:
    name: batfish.base
- name: Execute Batfish related tasks
  block:
  - name: Setup connection to Batfish service
    bf_session:
      host: 192.168.100.5
      name: batfish

  - name: Initialize the DevSecOps network
    bf_init_snapshot:
      network: dso_network
      snapshot: dso_snapshot
      snapshot_data: ./batfish/networks/
      overwrite: true

  # List of Assertions for Batfish Ansible - https://github.com/batfish/ansible/blob/master/docs/assertions.rst
  # List of Assertions - https://batfish.readthedocs.io/en/latest/asserts.html
  # Header constraints - https://batfish.readthedocs.io/en/latest/datamodel.html#pybatfish.datamodel.flow.HeaderConstraints
  - name: Validate that a service is reachable from outside the network
    bf_assert:
      assertions:
        # - type: assert_all_flows_succeed
        - type: assert_all_flows_succeed
          name: Confirm R1 Pod Number Loopback is reachable for TCP traffic from Intf Gig2 on R2
          parameters:
            startLocation: '@enter(r2[GigabitEthernet2.10])'
            headers:
              dstIps: "{{ loop_ip }}"
              # "{{ R1loopip | default('100.100.100.100')  }}"
              # applications: 'DNS'
              ipProtocols: 'tcp'
              dstPorts: '22'
    register: bf_assert
    ignore_errors: true

  - name: Display Batfish validation result details
    debug: msg="{{bf_assert}}"
    failed_when: >
      ("successfully" not in bf_assert.summary)

  delegate_to: localhost
  run_once: true
  vars:
    ansible_connection: local