---
- name: "Add {{ ansible_host }} to known_hosts"
  ansible.builtin.shell: "{{ item }}"
  delegate_to: localhost
  loop:
    - 'mkdir -p /root/.ssh/'
    - "ssh-keyscan -H {{ ansible_host }} >> ~/.ssh/known_hosts"
  vars:
    ansible_network_os: ios
