- name: Get Router Running Config
  cisco.ios.ios_command:
    commands: show run
  register: rtr_runcfg

- name: Save Router Running Config to router_configs
  copy:
    content: "{{ rtr_runcfg.stdout[0] }}"
    dest: "{{ playbook_dir }}/router_configs/{{ inventory_hostname }}_runcfg.cfg"

- name: Save Router Running Config to Batfish_configs
  copy:
    content: "{{ rtr_runcfg.stdout[0] }}"
    dest: "{{ playbook_dir }}/batfish/networks/configs/{{ inventory_hostname }}_runcfg.cfg"